### ISSUE TITLE
Add a setup.py file

### ISSUE THREAD

**Issue by waylan** [mayoff/python-markdown-mathjax#8]
The install instructions are the worst I have ever seen for a Python-Markdown extension:

> You can install the extension in one of two ways:

> -   You can put it right into your `python-markdown` installation.  Run this command:

 >         python -c 'import markdown; print markdown.__path__[0]'

>     That prints the path of the `markdown` module.  It should have a subdirectory named `extensions`.  Rename `mdx_mathjax.py` to `mathjax.py` and copy it to that `extensions` subdirectory.

 >      If `python-markdown` was installed as a zipped egg file, you won't find that `markdown/extensions` directory because it's inside the egg file.  You'll have to delete the egg file (you can find the name in the output of the command above) and reinstall it unzipped: `easy_install -Z Markdown`.  Then you should have a `markdown/extensions` directory in which to put `mathjax.py`.

You must be kidding me. I don't mean to be rude, but I can't imagine anyone doing this. And even then, the `markdown/extensions` directory is reserved for extensions which ship with Python-Markdown.

> -    You can put it in your `PYTHONPATH`.  If you do this, don't rename the file.  It needs to be named `mdx_mathjax.py`.

That is a little better (it actually follows the recommended way to install an extension), but only seasoned Python users will know what to do. Add a `setup.py` file and this becomes as easy as issuing a single command to both download and install:

    pip install git+https://github.com/mayoff/python-markdown-mathjax.git#egg=mathjax

Or three commands without pip:

    git clone https://github.com/mayoff/python-markdown-mathjax.git mathjax
    cd mathjax
    python setup.py install

Of course, once you have a `setup.py` file, you can also submit it to PyPI, which makes installing even easier.

**Comment by mayoff** [comment]
Thank you for your bug report.  In the future, if you don't mean to be rude, avoid phrases like "the worst I have ever seen" and "You must be kidding me" when sending unsolicited messages to strangers.

I have already spent as much time as I care to on this project, so I will not be adding a `setup.py` to it.
